#!/usr/bin/env python3
"""Vendor the web fonts used by learners.ai into `assets/fonts/`.

The site ships its own font binaries so that no third-party request is made at
runtime (better Lighthouse scores, no CDN outage, works offline from disk).

Usage:
    python3 scripts/fetch_fonts.py            # download missing subsets
    python3 scripts/fetch_fonts.py --force    # re-download everything

The script writes:
    assets/fonts/<family-slug>-<subset>.woff2
    assets/css/fonts.css

All three families are licensed under the SIL Open Font License 1.1, which
permits redistribution: see assets/fonts/OFL.txt for attribution. Fonts are
served from the Google Fonts CSS API (which is the distribution point named by
each project), so this script is the only network step in the whole project.
"""

from __future__ import annotations

import argparse
import pathlib
import re
import sys
import urllib.request

ROOT = pathlib.Path(__file__).resolve().parent.parent
FONT_DIR = ROOT / "assets" / "fonts"
CSS_OUT = ROOT / "assets" / "css" / "fonts.css"

# A modern browser UA is required: the Google Fonts API serves woff2 only to
# clients that advertise support for it, and TTF otherwise.
_BROWSER_UA = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
)

# Heading: geometric sans. Body: humanist sans. Metadata/pricing: monospace.
FAMILIES = [
    ("Space+Grotesk:wght@300..700", "space-grotesk"),
    ("IBM+Plex+Sans:wght@400;500;600", "ibm-plex-sans"),
    ("JetBrains+Mono:wght@400..700", "jetbrains-mono"),
]

# Latin is required; latin-ext keeps accented names (e.g. "Anthropic", "Claude
# Opus" accented variants, contributor names) from falling back to system fonts.
SUBSETS = ("latin", "latin-ext")

CSS_API = (
    "https://fonts.googleapis.com/css2?"
    + "&".join(f"family={q}" for q, _ in FAMILIES)
    + "&display=swap"
)

BLOCK_RE = re.compile(r"/\*\s*(?P<subset>[\w-]+)\s*\*/\s*(?P<block>@font-face\s*\{[^}]*\})")


def fetch(url: str) -> bytes:
    req = urllib.request.Request(url, headers={"User-Agent": _BROWSER_UA})
    with urllib.request.urlopen(req, timeout=30) as resp:  # noqa: S310 - fixed https URLs
        return resp.read()


def parse_blocks(css: str) -> list[dict[str, str]]:
    blocks = []
    for match in BLOCK_RE.finditer(css):
        block = match.group("block")
        family = re.search(r"font-family:\s*'([^']+)'", block)
        weight = re.search(r"font-weight:\s*([\d\s]+);", block)
        style = re.search(r"font-style:\s*(\w+)", block)
        url = re.search(r"url\((https://[^)]+\.woff2)\)", block)
        ranges = re.search(r"unicode-range:\s*([^;]+);", block)
        if not (family and weight and style and url):
            continue
        blocks.append(
            {
                "subset": match.group("subset"),
                "family": family.group(1),
                "weight": weight.group(1).strip(),
                "style": style.group(1),
                "url": url.group(1),
                "unicode_range": (ranges.group(1).strip() if ranges else ""),
            }
        )
    return blocks


def slug(text: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--force", action="store_true", help="re-download existing files")
    args = parser.parse_args()

    FONT_DIR.mkdir(parents=True, exist_ok=True)
    CSS_OUT.parent.mkdir(parents=True, exist_ok=True)

    print(f"→ GET {CSS_API}")
    css = fetch(CSS_API).decode("utf-8")
    blocks = [b for b in parse_blocks(css) if b["subset"] in SUBSETS]
    if not blocks:
        print("error: no matching @font-face blocks found in the Google Fonts response", file=sys.stderr)
        return 1

    rules: list[str] = []
    seen: dict[str, str] = {}  # remote url -> local filename
    for block in blocks:
        remote = block["url"]
        if remote not in seen:
            filename = f"{slug(block['family'])}-{block['subset']}.woff2"
            dest = FONT_DIR / filename
            if dest.exists() and not args.force:
                print(f"  = {filename} (cached)")
            else:
                print(f"  ↓ {filename}")
                dest.write_bytes(fetch(remote))
            seen[remote] = filename

        rules.append(
            "@font-face {\n"
            f"  font-family: '{block['family']}';\n"
            f"  font-style: {block['style']};\n"
            f"  font-weight: {block['weight']};\n"
            "  font-display: swap;\n"
            f"  src: url('../fonts/{seen[remote]}') format('woff2');\n"
            f"  unicode-range: {block['unicode_range']};\n"
            "}"
        )

    header = (
        "/* Generated by scripts/fetch_fonts.py - do not edit by hand.\n"
        "   Space Grotesk, IBM Plex Sans and JetBrains Mono are licensed under\n"
        "   the SIL Open Font License 1.1 (see assets/fonts/OFL.txt). */\n\n"
    )
    CSS_OUT.write_text(header + "\n\n".join(rules) + "\n", encoding="utf-8")
    print(f"✓ wrote {CSS_OUT.relative_to(ROOT)} ({len(seen)} font files, {len(rules)} rules)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
